services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mariadb_data:/var/lib/mysql

  fastapi:
    build: 
      context: .
      dockerfile: ./StudentProfesorDisciplineAPI/Dockerfile
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
    ports:
      - "8000:80" 
    networks:
      - app-network
    depends_on:
      - mariadb
    restart: always

  material_api:
    build:
      context : .
      dockerfile : ./MaterialeAPI\Dockerfile
    ports:
      - "9090:9090"

    environment:
      - DB_ADMIN_USERNAME = rootcezar
      - DB_ADMIN_PASSWORD = rootcezarpass
      - ME_CONFIG_MONGODB_URL=mongodb://rootcezar:rootcezarpass@mongo:27017/
    restart: on-failure


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootcezar
      MONGO_INITDB_ROOT_PASSWORD: rootcezarpass
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootcezar
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootcezarpass
      ME_CONFIG_MONGODB_URL: mongodb://rootcezar:rootcezarpass@mongo:27017/
      ME_CONFIG_BASICAUTH: false



networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
